name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wgtechlabs/release-build-flow-action@v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
